apiVersion: v1
kind: Service
metadata:
  name: klovercloud-ci-ctl
  namespace: klovercloud
  labels:
    app: klovercloud-ci-ctl
spec:
  ports:
  - name: http-rest
    port: 80
    targetPort: 8080
  selector:
    app: klovercloud-ci-ctl